# Jasypt encryption
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    password: hong8159

#Server Encoding
server:
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true


#Spring Setting
spring :
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spring?serverTimezone=UTC&useSSL=false
    #username : hong
    #password : 8159
    username : root
    password : root

  jpa:
    show-sql : true
    database-platform: org.hibernate.dialect.MySQL8Dialect

    hibernate:
      ddl-auto: create


# JWT Secret-key
  jwt:
    key: grayson
    validity : 5*60*60