POST http://localhost:8080/api/board/1/comment
Content-Type: application/json

{
  "contents" : "테스트 댓글1",
  "writer" : "홍근호1"
}



###POST http://localhost:8080/api/board
Content-Type: application/json

{
  "title" : "graon2231",
  "contents" : "홍근호",
  "writer" : "password"
}


### POST http://localhost:8080/api/user
Content-Type: application/json

{
     "userId" : "graon2231",
     "userName" : "홍근호",
     "userPw" : "password",
     "userPhoneNumber" : "010-7212-8121",
     "userBirthDate" : "1994-01-01"
}


### 멤버 아이디 조회 서비스 테스트
GET http://localhost:8080/api/members/exist/memberId/grayson

### 멤버 핸드폰 번호 조회 서비스 테스트
GET http://localhost:8080/api/members/exist/phone/010-7122-8114
